# Display a box
print("##########")
print("#  o  o  #")
print("#   __   #")
print("##########")
print("   ####      \\/")
print("##########   #")
print("#        #   #")
print("# HELLO  #####")
print("#        #")
print("##########")
print("###    ###")
print("###    ###")