# Display a box
print("##########")
print("#  *  *  #")
print("#   __   #")
print("##########")
print("   ####      \/")
print("##########   #")
print("#        #   #")
print("#        #####")
print("#        #")
print("##########")
print("###    ###")
print("###    ###")